apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec: 
  # minReadySeconds: 30
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:    # template for the pods
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: arm64v8/mongo:4.0