apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: arm64v8/mongo:4.0
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        hostPath:
          path: /mnt/some/directory/structure/
          type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongodb

spec:
  selector:
    app: mongodb
  ports:
    - name: mongoport
      port: 27017
  type: ClusterIP

---
