apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec: 
  # minReadySeconds: 30
  replicas: 1
  selector:
    matchLabels:
      app: queue
  template:    # template for the pods
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - name: queue
        image: richardchesterwood/k8s-fleetman-queue:release1-arm64